N: 720

max_speed: 0.35
min_speed: 0.1
max_yawrate: 0.85
max_accel: 5.0
max_dyawrate: 2.0          
 
v_reso: 0.05
yawrate_reso: 0.05

dt: 0.1
predict_time: 3.0

to_goal_cost_gain: 1.0
speed_cost_gain: 1.0

robot_radius: 0.25

roomba_v_gain: 0.2
roomba_omega_gain: 0.2
                        
