N: 720

max_speed: 0.30
min_speed: 0.1
max_yawrate: 0.80
max_accel: 4.0
max_dyawrate: 1.5         
 
v_reso: 0.05
yawrate_reso: 0.05

dt: 0.1
predict_time: 3.0

to_goal_cost_gain: 1.2
dist_gain: 2.0
speed_cost_gain: 0.5
obstacle_cost_gain: 0.5

robot_radius: 0.25

roomba_v_gain: 0.6
roomba_omega_gain: 0.6
                        
